### PR TITLE
[WGAN] Added a missing required reading and fixed a link

### PR DESCRIPTION
**Pull request by JamesAllingham**
Whoops, I'm not sure how this ended up being missed! Or why I only caught it now... but anyways, here is a fix.

### CODE REVIEW

**Comment by cinjon** [comment]
nice! however, can't rebase this in because there are conflicts. mind fixing this?

**Comment by JamesAllingham** [comment]
> 
> 
> nice! however, can't rebase this in because there are conflicts. mind fixing this?

Happy to... but slightly confused :P Where are the conflicts? GitHub has the big green banner telling me that there are no conflicts with the base branch, and I've been able to merge this branch into master locally.

**Comment by cinjon** [comment]
Screen Shot 2019-10-03 at 8 55 09 AM

**Comment by cinjon** [comment]
... awkward. lol. hmm.

**Comment by JamesAllingham** [comment]
awkward

**Comment by JamesAllingham** [comment]
Awkward indeed :P

**Comment by cinjon** [comment]
what happens if you do a completely clean branch and then just add these two changes on top?

**Comment by JamesAllingham** [comment]
I'll try that...

**Comment by JamesAllingham** [comment]
So also seems to work, should I open a PR for that and we can see if it looks good on your side?

**Comment by cinjon** [comment]
Yup, let's do that.

**Pull request closed without merging**
